<?php

return array(
    'choose_a_schema' => 'Choose a schema',
    'add_new_record' => 'Add New Record',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'save' => 'Save',
    'error' => 'Error',
    'content' => 'Content',
    'last_modified' => 'Last modified',
    'actions' => 'Actions',
    'created' => 'Created',
    'updated' => 'Updated',
    'admin' => 'ADMIN',
    'home' => 'home',
    'schemas' => 'Schemas',
    'current' => 'Current',
    'delete_confirmation' => 'Delete record. Are you sure you want to do this?',
    'content_management' => 'Content Management',
    'media_management' => 'Media Management',
    'manage_images' => 'Upload and manage your images',
    'open_media_manager' => 'Open Media Manager',
    'upload_image' => 'Upload Image',
    'select_image' => 'Select Image',
    'supported_formats' => 'Supported formats',
    'max_size' => 'Max size',
    'upload' => 'Upload',
    'uploaded_images' => 'Uploaded Images',
    'no_images_uploaded' => 'No images have been uploaded yet.',
    'delete_image_confirm' => 'Are you sure you want to delete this image?',
    'no_image_selected' => 'No image selected',
    'selected_image' => 'Selected Image',
    'clear_selection' => 'Clear Selection',
    'choose_image' => 'Choose Image',
    'select_from_uploaded_images' => 'Select from Uploaded Images',
    'upload_images_from_media' => 'Please upload images from Media Management:',
    'caption' => 'Caption',
    'no_images_selected' => 'No images selected',
    'add_image' => 'Add Image',
    'image_already_added' => 'This image has already been added',
);
