<?php

return array(
    'choose_a_schema' => 'スキーマを選択してください',
    'add_new_record' => '新しいレコードを追加',
    'edit' => '編集',
    'delete' => '削除',
    'save' => '保存',
    'error' => 'エラー',
    'content' => 'コンテンツ',
    'last_modified' => '最終更新',
    'actions' => 'アクション',
    'created' => '作成日時',
    'updated' => '更新日時',
    'admin' => '管理画面',
    'home' => 'ホーム',
    'schemas' => 'スキーマ',
    'current' => '現在',
    'delete_confirmation' => 'レコードを削除します。本当によろしいですか？',
    'content_management' => 'コンテンツ管理',
    'media_management' => 'メディア管理',
    'manage_images' => '画像のアップロードと管理',
    'open_media_manager' => 'メディア管理を開く',
    'upload_image' => '画像をアップロード',
    'select_image' => '画像を選択',
    'supported_formats' => '対応形式',
    'max_size' => '最大サイズ',
    'upload' => 'アップロード',
    'uploaded_images' => 'アップロード済み画像',
    'no_images_uploaded' => 'まだ画像がアップロードされていません。',
    'delete_image_confirm' => 'この画像を削除してもよろしいですか？',
    'no_image_selected' => '画像なし',
    'selected_image' => '選択中の画像',
    'clear_selection' => '選択をクリア',
    'choose_image' => '画像を選択',
    'select_from_uploaded_images' => 'アップロード済み画像から選択',
    'upload_images_from_media' => '画像はメディア管理からアップロードしてください：',
);